# Generated by Django 4.2.6 on 2023-10-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_tags_alter_ad_owner_alter_fav_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='price',
            new_name='salary',
        ),
    ]
